# Generated by Django 5.2.1 on 2025-05-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_permission_custompermission_alter_log_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('PASSWORD_RESET', 'Redefinição de senha'), ('PERMISSION_CHANGE', 'Mudança de permissão'), ('ACCOUNT_LOCKED', 'Conta bloqueada')], default='LOGIN', max_length=50),
        ),
        migrations.AddField(
            model_name='log',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
