# Generated by Django 5.2.1 on 2025-05-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_log_action_type_log_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_RESET', 'Redefinição de senha'), ('PASSWORD_CHANGE', 'Alteração de senha'), ('PERMISSION_CHANGE', 'Mudança de permissão'), ('ACCOUNT_LOCKED', 'Conta bloqueada'), ('REGISTER', 'Cadastro'), ('CREATE', 'Criação'), ('READ', 'Consulta'), ('UPDATE', 'Atualização'), ('DELETE', 'Exclusão'), ('OTHER', 'Outro')], default='LOGIN', max_length=50),
        ),
    ]
